### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by maconleary** [PokeNavBot/pokenav-documentation#12]
I am willing to update the text of the documentation to cover anything I can find mentioned in #announcements plus any undocumented features I've heard about along the way, but have completely bounced off the GitHub interface and would not be able to do it in GitHub.

If an alternative would be possible, let me know.

**Comment by dandesousa** [comment]
I'm working on a better automated documentation method

**Comment by dandesousa** [comment]
We can discuss this more in the discord
